export const USE_SELETEC_QUANTILY = "USE_SELETEC_QUANTILY";
export const UP_QUANTITY_PRODUCT_CAR = "UP_QUANTITY_PRODUCT";
export const DOWN_QUANTITY_PRODUCT_CAR = "DOWN_QUANTITY_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
